# Generated by Django 4.0.1 on 2023-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='cor_carro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='modelo_carro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='placa_carro',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='tem_carro',
            field=models.BooleanField(default=False),
        ),
    ]
