# Generated by Django 4.0.1 on 2023-05-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_visitante_cor_carro_visitante_modelo_carro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='tem_carro',
            new_name='uber',
        ),
    ]
