# Generated by Django 4.0.1 on 2023-05-05 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0004_rename_apartamento_visitante_apartamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$', 'CPF inválido. O formato deve ser: 000.000.000-00')]),
        ),
    ]
