# Generated by Django 4.0.1 on 2023-05-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0005_alter_visitante_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='alterado_por',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='criado_navegador',
            field=models.TextField(blank=True, null=True, verbose_name='Criado no Navegador'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='criado_por',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='editado_navegador',
            field=models.TextField(blank=True, null=True, verbose_name='Editado no Navegador'),
        ),
    ]
