# Generated by Django 4.0.1 on 2023-05-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0006_visitante_alterado_em_visitante_alterado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='criado_navegador',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='editado_navegador',
        ),
    ]
